### ISSUE TITLE
A small mistake

### ISSUE THREAD

**Issue by wjinfeng** [HIT-SCIR/Molweni#2]
in DP train set, id is 9357, there is a relation named "C" between utterance 3 and 2
in detail
ahmad: you want me to paste this all in here
gnomefreak: the first line of that file it says something like deb cdrom ?
gnomefreak: please put a sign infront of the word deb in that line
ahmad: it wont let me edit it
...
I guess it would be "Comment"
Thank you again for this high quality data set

**Comment by jackylee1993** [comment]
Thank you! I just revise the mistake.
